package Menu2_Laundry;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.table.TableColumnModel;

public class Menu_OutletADM extends javax.swing.JFrame {
    private DefaultTableModel model = null; 
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    private int id_user  = 0, id_outlet = 0;
    String role = "";
    String username="";
    
    public Menu_OutletADM() {
        initComponents();
        k.connect();
        refreshTable();
        Renderer.setCenterBoldColumnHeaders(tblOutlet);
    }
    
    public void setId_user(int id_user) {
        this.id_user = id_user;
    }

    public void setId_outlet(int id_outlet) {
        this.id_outlet = id_outlet;
    }
    
    public void setUsername(String username) {
        this.username = username;
        tSelamatDatang.setText("Halo, "+username);
    }
    
    public void setRole(String role) {
        this.role = role;
        if (this.role.equals("admin")){          
            btnUser.setEnabled(true);
            btnTransaksi.setEnabled(true);
            btnMember.setEnabled(true);
            btnOutlet.setEnabled(true);
            btnPaket.setEnabled(true);
        } else if (this.role.equals("kasir")){
            btnTransaksi.setEnabled(true);
            btnMember.setEnabled(true);
            btnUser.setVisible(false);
            btnOutlet.setVisible(false);
            btnPaket.setVisible(false);
        } else if (this.role.equals("owner")){
            btnTransaksi.setVisible(false);
            btnMember.setVisible(false);
            btnUser.setVisible(false);
            btnOutlet.setVisible(false);
            btnPaket.setVisible(false);
        }
        tSelamatDatang.setText("Halo, "+username);
    }
    
    public void refreshTable () {
        model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("No Telepon");
        tblOutlet.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("select * "
                    + "from tb_outlet");
            this.rs = stat.executeQuery();
            int rowNum = 1;
            
            while (rs.next()) {
                Object[] data = {
                    rowNum,
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                };
                model.addRow(data);
                rowNum++;
            }
            TableColumnModel columnModel = tblOutlet.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(20);
            columnModel.getColumn(1).setPreferredWidth(30);         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        tIdOutlet.setText("");
        tNamaOutlet.setText("");
        tAlamatOutlet.setText("");
        tNoTelepon.setText("");
        Renderer.setCenterBoldColumnHeaders(tblOutlet);
    }
    
    private boolean isFormValid() {
        if (tNamaOutlet.getText().isEmpty() || tAlamatOutlet.getText().isEmpty() 
                || tNoTelepon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua form "
                    + "harus diisi!", "Peringatan", 
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tNamaPengguna = new javax.swing.JTextField();
        tKataSandi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMasuk = new javax.swing.JButton();
        tMasuk = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnOutlet = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnPaket = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jPanelGradient3 = new jpanelgradient.JPanelGradient();
        tSelamatDatang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tIdOutlet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tNamaOutlet = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tAlamatOutlet = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        tNoTelepon = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOutlet = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        tCariOutlet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxUrutkan = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(91, 134, 229));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        tNamaPengguna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(91, 134, 229)));
        tNamaPengguna.setMaximumSize(new java.awt.Dimension(60, 20));
        tNamaPengguna.setMinimumSize(new java.awt.Dimension(60, 20));
        tNamaPengguna.setPreferredSize(new java.awt.Dimension(60, 20));
        tNamaPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaPenggunaActionPerformed(evt);
            }
        });
        jPanel2.add(tNamaPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 270, 30));

        tKataSandi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(91, 134, 229)));
        tKataSandi.setMaximumSize(new java.awt.Dimension(60, 20));
        tKataSandi.setMinimumSize(new java.awt.Dimension(60, 20));
        tKataSandi.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel2.add(tKataSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 270, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(91, 134, 229));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Lupa Kata Sandi?");
        jLabel5.setPreferredSize(new java.awt.Dimension(57, 20));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 270, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(91, 134, 229));
        jLabel6.setText("Nama Pengguna");
        jLabel6.setPreferredSize(new java.awt.Dimension(57, 20));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 270, 30));

        btnMasuk.setBackground(new java.awt.Color(91, 134, 229));
        btnMasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMasuk.setForeground(new java.awt.Color(255, 255, 255));
        btnMasuk.setText("Masuk");
        btnMasuk.setMaximumSize(new java.awt.Dimension(50, 40));
        btnMasuk.setMinimumSize(new java.awt.Dimension(50, 40));
        btnMasuk.setPreferredSize(new java.awt.Dimension(50, 40));
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        jPanel2.add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 270, 50));

        tMasuk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tMasuk.setForeground(new java.awt.Color(91, 134, 229));
        tMasuk.setText("Masuk");
        jPanel2.add(tMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 19, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(91, 134, 229));
        jLabel7.setText("Kata Sandi");
        jLabel7.setPreferredSize(new java.awt.Dimension(57, 20));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 270, 30));

        jPanel2.getAccessibleContext().setAccessibleParent(jPanel1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(91, 134, 229));

        btnOutlet.setBackground(new java.awt.Color(91, 134, 229));
        btnOutlet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOutlet.setForeground(new java.awt.Color(255, 255, 255));
        btnOutlet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon Outlet.png"))); // NOI18N
        btnOutlet.setText("Outlet");
        btnOutlet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOutlet.setIconTextGap(15);
        btnOutlet.setMaximumSize(new java.awt.Dimension(90, 27));
        btnOutlet.setMinimumSize(new java.awt.Dimension(90, 27));
        btnOutlet.setPreferredSize(new java.awt.Dimension(90, 27));
        btnOutlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutletActionPerformed(evt);
            }
        });

        btnUser.setBackground(new java.awt.Color(91, 134, 229));
        btnUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon User.png"))); // NOI18N
        btnUser.setText("User");
        btnUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUser.setIconTextGap(15);
        btnUser.setMaximumSize(new java.awt.Dimension(90, 27));
        btnUser.setMinimumSize(new java.awt.Dimension(90, 27));
        btnUser.setPreferredSize(new java.awt.Dimension(90, 27));
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        btnPaket.setBackground(new java.awt.Color(91, 134, 229));
        btnPaket.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPaket.setForeground(new java.awt.Color(255, 255, 255));
        btnPaket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon Pakeet.png"))); // NOI18N
        btnPaket.setText("Paket");
        btnPaket.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPaket.setIconTextGap(15);
        btnPaket.setMaximumSize(new java.awt.Dimension(90, 27));
        btnPaket.setMinimumSize(new java.awt.Dimension(90, 27));
        btnPaket.setPreferredSize(new java.awt.Dimension(90, 27));
        btnPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaketActionPerformed(evt);
            }
        });

        btnMember.setBackground(new java.awt.Color(91, 134, 229));
        btnMember.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMember.setForeground(new java.awt.Color(255, 255, 255));
        btnMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon Member.png"))); // NOI18N
        btnMember.setText("Member");
        btnMember.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMember.setIconTextGap(15);
        btnMember.setMaximumSize(new java.awt.Dimension(90, 27));
        btnMember.setMinimumSize(new java.awt.Dimension(90, 27));
        btnMember.setPreferredSize(new java.awt.Dimension(90, 27));
        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });

        btnLaporan.setBackground(new java.awt.Color(91, 134, 229));
        btnLaporan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon Cetak Laporan.png"))); // NOI18N
        btnLaporan.setText("Cetak Laporan");
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporan.setIconTextGap(15);
        btnLaporan.setMaximumSize(new java.awt.Dimension(90, 27));
        btnLaporan.setMinimumSize(new java.awt.Dimension(90, 27));
        btnLaporan.setPreferredSize(new java.awt.Dimension(90, 27));
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(91, 134, 229));
        btnTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon Transaksi.png"))); // NOI18N
        btnTransaksi.setText("Transaksi");
        btnTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaksi.setIconTextGap(15);
        btnTransaksi.setMaximumSize(new java.awt.Dimension(90, 27));
        btnTransaksi.setMinimumSize(new java.awt.Dimension(90, 27));
        btnTransaksi.setPreferredSize(new java.awt.Dimension(90, 27));
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(91, 134, 229));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon Keluar.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKeluar.setIconTextGap(15);
        btnKeluar.setMaximumSize(new java.awt.Dimension(90, 27));
        btnKeluar.setMinimumSize(new java.awt.Dimension(90, 27));
        btnKeluar.setPreferredSize(new java.awt.Dimension(90, 27));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMember, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOutlet, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMember, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, 600));

        jPanelGradient3.setColoerEnd(new java.awt.Color(91, 134, 229));
        jPanelGradient3.setColorStart(new java.awt.Color(54, 209, 220));
        jPanelGradient3.setMaximumSize(new java.awt.Dimension(400, 600));
        jPanelGradient3.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanelGradient3.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanelGradient3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tSelamatDatang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tSelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        tSelamatDatang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tSelamatDatang.setText("Halo, Admin!");
        tSelamatDatang.setToolTipText("");
        jPanelGradient3.add(tSelamatDatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel3.add(jPanelGradient3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Kelola Outlet");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 680, 50));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tIdOutlet.setEnabled(false);
        tIdOutlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdOutletActionPerformed(evt);
            }
        });
        jPanel5.add(tIdOutlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 500, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ID Outlet");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nama Outlet");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 40));

        tNamaOutlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaOutletActionPerformed(evt);
            }
        });
        jPanel5.add(tNamaOutlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 500, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("No Telepon");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 40));

        tAlamatOutlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAlamatOutletActionPerformed(evt);
            }
        });
        jPanel5.add(tAlamatOutlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 500, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Alamat Outlet");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 40));

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel5.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 140, 40));

        btnTambah.setBackground(new java.awt.Color(91, 134, 229));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel5.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 213, 140, 40));

        btnUbah.setBackground(new java.awt.Color(255, 153, 51));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel5.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 140, 40));

        tNoTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNoTeleponActionPerformed(evt);
            }
        });
        jPanel5.add(tNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 500, 40));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 500, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 680, 270));

        tblOutlet.setAutoCreateRowSorter(true);
        tblOutlet.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblOutlet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, "", null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "ID Outlet", "Nama Outlet", "Alamat Outlet", "No Telepon"
            }
        ));
        tblOutlet.setFocusable(false);
        tblOutlet.setRowHeight(25);
        tblOutlet.setShowHorizontalLines(true);
        tblOutlet.setShowVerticalLines(true);
        tblOutlet.getTableHeader().setReorderingAllowed(false);
        tblOutlet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOutletMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOutlet);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 680, 200));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Cari Outlet");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 100, 40));

        tCariOutlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariOutletActionPerformed(evt);
            }
        });
        jPanel3.add(tCariOutlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 210, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Urutkan");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 100, 40));

        cbxUrutkan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxUrutkan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "ID Outlet", "Nama Outlet", "Alamat" }));
        cbxUrutkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUrutkanActionPerformed(evt);
            }
        });
        jPanel3.add(cbxUrutkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 190, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasukActionPerformed

    private void tNamaPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaPenggunaActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        Menu_Login2 l = new Menu_Login2();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        Menu_UtamaADM m = new Menu_UtamaADM();
        m.setId_user(id_user);
        m.setId_outlet(id_outlet);
        m.setRole(role);
        m.setUsername(username);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        Menu_Cetak m = new Menu_Cetak();
        m.setId_user(id_user);
        m.setId_outlet(id_outlet);
        m.setRole(role);
        m.setUsername(username);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        // TODO add your handling code here:
        Menu_MemberADM m = new Menu_MemberADM();
        m.setId_user(id_user);
        m.setId_outlet(id_outlet);
        m.setRole(role);
        m.setUsername(username);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMemberActionPerformed

    private void btnPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaketActionPerformed
        // TODO add your handling code here:
        Menu_PaketADM m = new Menu_PaketADM();
        m.setId_user(id_user);
        m.setId_outlet(id_outlet);
        m.setRole(role);
        m.setUsername(username);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPaketActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        Menu_UserADM m = new Menu_UserADM();
        m.setId_user(id_user);
        m.setId_outlet(id_outlet);
        m.setRole(role);
        m.setUsername(username);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnOutletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutletActionPerformed
        // TODO add your handling code here:
        refreshTable();
        cbxUrutkan.setSelectedItem("PILIH");
    }//GEN-LAST:event_btnOutletActionPerformed

    private void tIdOutletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdOutletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdOutletActionPerformed

    private void tNamaOutletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaOutletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaOutletActionPerformed

    private void tAlamatOutletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAlamatOutletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAlamatOutletActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int x;
    
        x = JOptionPane.showConfirmDialog(null, "Yakin Ingin "
                + "Menghapus Data?", "Konfirmasi", JOptionPane.
                        YES_NO_OPTION);
        
        if (x == JOptionPane.YES_OPTION) {
            try {
                this.stat = k.getCon().prepareStatement("delete from "
                        + "tb_outlet where id_outlet=?");
                stat.setString(1, tIdOutlet.getText());
                stat.executeUpdate();
                refreshTable();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, 
                        e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if (isFormValid()) {
            try {
                this.stat = k.getCon().prepareStatement("insert into tb_outlet "
                        + "values (?,?,?,?)");
               stat.setInt(1, 0);
                stat.setString(2, tNamaOutlet.getText());
                stat.setString(3, tAlamatOutlet.getText());
                stat.setString(4, tNoTelepon.getText());
                stat.executeUpdate();
                refreshTable();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        e.getMessage());
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try {
            this.stat = k.getCon().prepareStatement("update tb_outlet "
                    + "set nama=?, alamat=?, tlp=? where id_outlet=?");
            stat.setString(1, tNamaOutlet.getText());
            stat.setString(2, tAlamatOutlet.getText());
            stat.setString(3, tNoTelepon.getText());
            stat.setString(4, tIdOutlet.getText());
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
                    e.getMessage());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tNoTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNoTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNoTeleponActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void tblOutletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOutletMouseClicked
        // TODO add your handling code here:
        tIdOutlet.setText(model.getValueAt(tblOutlet.getSelectedRow(), 
                1).toString());
        tNamaOutlet.setText(model.getValueAt(tblOutlet.getSelectedRow(), 
                2).toString());
        tAlamatOutlet.setText(model.getValueAt(tblOutlet.getSelectedRow(), 
                3).toString());
        tNoTelepon.setText(model.getValueAt(tblOutlet.getSelectedRow(), 
                4).toString());
    }//GEN-LAST:event_tblOutletMouseClicked

    private void tCariOutletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariOutletActionPerformed
        // TODO add your handling code here:
        String cari = tCariOutlet.getText();
        DefaultTableModel tableModel = (DefaultTableModel) tblOutlet.getModel();
        tableModel.setRowCount(0);

        try {
            String query = "SELECT * FROM tb_outlet WHERE id_outlet LIKE ? "
                    + "OR nama LIKE ? OR alamat LIKE ?";
            this.stat = k.getCon().prepareStatement(query);
            this.stat.setString(1, "%" + cari + "%");
            this.stat.setString(2, "%" + cari + "%");
            this.stat.setString(3, "%" + cari + "%");
            this.rs = stat.executeQuery();
            int rowNum = 1;

            while (rs.next()) {
                Object[] data = {
                    rowNum,          // Add the row number
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                };
                tableModel.addRow(data);
                rowNum++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
                    e.getMessage());
        }
    }//GEN-LAST:event_tCariOutletActionPerformed

    private void cbxUrutkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUrutkanActionPerformed
        // TODO add your handling code here:
        String cari = tCariOutlet.getText();
        String urutan = cbxUrutkan.getSelectedItem().toString();

        DefaultTableModel tableModel = (DefaultTableModel) tblOutlet.getModel();
        tableModel.setRowCount(0);

        try {
            String query;
            if (urutan.equals("PILIH")) {
                query = "SELECT * FROM tb_outlet WHERE id_outlet LIKE ? OR nama"
                        + " LIKE ? OR alamat LIKE ?";
            } else {
                query = "SELECT * FROM tb_outlet WHERE id_outlet LIKE ? OR nama"
                        + " LIKE ? OR alamat LIKE ? ORDER BY ";
                if (urutan.equals("ID Outlet")) {
                    query += "id_outlet";
                } else if (urutan.equals("Nama Outlet")) {
                    query += "nama";
                } else if (urutan.equals("Alamat")) {
                    query += "alamat";
                }
            }

            this.stat = k.getCon().prepareStatement(query);
            this.stat.setString(1, "%" + cari + "%");
            this.stat.setString(2, "%" + cari + "%");
            this.stat.setString(3, "%" + cari + "%");

            this.rs = stat.executeQuery();
            int rowNum = 1;

            while (rs.next()) {
                Object[] data = {
                    rowNum,
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                };
                tableModel.addRow(data);
                rowNum++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
                    e.getMessage());
        }
    }//GEN-LAST:event_cbxUrutkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_OutletADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_OutletADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_OutletADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_OutletADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_OutletADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnOutlet;
    private javax.swing.JButton btnPaket;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUser;
    private javax.swing.JComboBox<String> cbxUrutkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private jpanelgradient.JPanelGradient jPanelGradient3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField tAlamatOutlet;
    private javax.swing.JTextField tCariOutlet;
    private javax.swing.JTextField tIdOutlet;
    private javax.swing.JTextField tKataSandi;
    private javax.swing.JLabel tMasuk;
    private javax.swing.JTextField tNamaOutlet;
    private javax.swing.JTextField tNamaPengguna;
    private javax.swing.JTextField tNoTelepon;
    private javax.swing.JLabel tSelamatDatang;
    private javax.swing.JTable tblOutlet;
    // End of variables declaration//GEN-END:variables
}
